In [1]:
import torch

In [2]:
def sigmoid_activation(x):
    """ Sigmoid activation function
        Arguments:
        x: torch.Tensor
        returns the pr
    """
    return 1/(1+torch.exp(-x))


a = torch.tensor(-15055)

sigmoid_activation(a)

tensor(0.)

In [3]:
# Generate some random data
torch.manual_seed(7)

In [4]:
# Features
features = torch.randn((1,5))# Sample input according to the normal distribution, 1 row, 5 columns
weights = torch.randn_like(features)# Random weights 1 row, 5 columns
bias = torch.randn((1,1))# Bias

In [5]:
features

tensor([[-0.1468,  0.7861,  0.9468, -1.1143,  1.6908]])

In [6]:
weights

tensor([[-0.8948, -0.3556,  1.2324,  0.1382, -1.6822]])

In [7]:
bias

tensor([[0.3177]])

In [8]:
y = sigmoid_activation(torch.sum(features*weights) + bias)

In [9]:
y

tensor([[0.1595]])